# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
source 'git@git.yupaopao.com:terminal/ios/component/YppSpec.git'


target 'Network' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Network
  pod 'Network', :path => '../'

end
